import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      Result1: "",
      Result2: "",
      Result3: "",
      ClassResult3: "columnNoneResult"
    };
    this.Solve = this.Solve.bind(this);
    this.ShowAnswer = this.ShowAnswer.bind(this);
  }
  
  Solve() {
    var Multiple3=0;
    var Multiple5=0;
    var Multiple15=0;
    var FinalResult=0;

    for (var i = 1; i <1000; i++) {
        if((i % 3) == 0){
          Multiple3 = Multiple3 + i;
        }
        if((i % 5) == 0){
          Multiple5 = Multiple5 + i;
        }
        if((i % 15) == 0){
          Multiple15 = Multiple15 + i;
        }
    } 
    FinalResult = Multiple3 + Multiple5 - Multiple15;
    this.setState(
      {

        Result1: FinalResult 
      }
    )
  }

  ShowAnswer(){
    this.setState(
      {
        Result3: "123",
        ClassResult3: "columnResult"
      }
    )
  }

  render(){
    return(
      <div className="app">
        <header className="App-header">
          <h1 className="App-title">Project Euler</h1>
        </header>
        <div className="container">
          <div className="column">
            <article className="problem">
              <h2 className="problem_title">Multiples of 3 and 5</h2>
              <p className="problem_description">If we list all natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.</p>
              <p className="problem_Question">Find the sum of all the multiples of 3 or 5 below 1000.</p>
              <button className="problem_btn" onClick={this.Solve}>Solve</button>
              <p className="problem_Answer1">The answer is: {this.state.Result1}</p>
            </article>
          </div>
          <div className="column">
            <article className="problem">
              <h2 className="problem_title">Even Fibonacci numbers</h2>
              <p className="problem_description">Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
              <p className="problem_Question">By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
              <button className="problem_btn">Pop Solution</button>
            </article>
          </div>
          <div className="column">
            <article className="problem">
              <h2 className="problem_title">Power digit sum</h2>
              <p className="problem_description">215 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.</p>
              <p className="problem_Question">What is the sum of the digits of the number 21000?</p>
              <button className="problem_btn" onClick={this.ShowAnswer}>Show Answer</button >
            </article>
          </div>
          <div className="column">
            <article className={this.state.ClassResult3}>
              <h2 className="columnResult_title">The Answer is</h2>
              <p className="columnResult_result">{this.state.Result3}</p>
            </article>
          </div>
        </div>    
      </div>
    );
  }
}


export default App;
